### ISSUE TITLE
Idea on how to add some network features to the consistent hashring

### ISSUE THREAD

**Issue by Tochemey** [cruzelx/DSA-with-golang#1]
Hello @cruzelx thanks for this great piece of work. I would like to know whether you can give me some pointers on how to add some network features. However I have some few questions to ask:

1. How many can be run on a single node?
2. Can we have a cluster of Managers

From your implementation I assume we can only have one manager in a cluster of nodes.

**Comment by cruzelx** [comment]
Hey @Tochemey, I have another repository with consistent hashing implementation for my Distributed Cache System at https://github.com/cruzelx/Distributed-Cache-System. Please look at this for references. You will find how network calls are implemented. 

There are two ways you can go about it depending on the requirements. You can either make the manager node separate from the cache node which is mentioned in the above repository. The state of the manager nodes can be synced with Raft or Zookeeper. Note: I have not implemented Raft or Zookeeper in the above repository. 

The other way is to make both the manager and the cache node a single unit node. (cache + hashring = node) Then using raft a leader node can be elected. You can use a load balancer in front of the nodes as well. So, whenever a request is made, it is forwarded to one of the nodes. Since all the hashring are in sync, any incoming requests would be forwarded to the appropriate node. If the request ends up within the same node, no network call is made. You even make replica nodes which would require further clarification. If you need further clarification, feel free to contact me.

**Comment by Tochemey** [comment]
@cruzelx Thanks for the reply. I thought as much of raft because of the manager code. I will take a look at that repository.

**Comment by Tochemey** [comment]
@cruzelx I was thinking of the design of groupcache.
By the way I have in mind a project about distributed caching with data sharding that can integrate with any discovery service like:

- NATs
- Kubernetes
- etc...

I will be glad to talk about it if you are open to it.

**Comment by cruzelx** [comment]
@Tochemey Definitely, we can talk about it. Regarding groupcache, I need to have a look at it.
